version: '3.8'

services:
  mcp-server:
    build: .
    container_name: mcp-server
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://mcp_user:mcp_password@postgres:5432/mcp_tasks
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - mcp-network
    stdin_open: true
    tty: true
    volumes:
      - ./schema_properties.json:/app/schema_properties.json:ro

  postgres:
    image: postgres:15
    container_name: mcp-postgres
    environment:
      POSTGRES_DB: mcp_tasks
      POSTGRES_USER: mcp_user
      POSTGRES_PASSWORD: mcp_password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ../database/seed.sql:/docker-entrypoint-initdb.d/02-seed.sql
    networks:
      - mcp-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mcp_user -d mcp_tasks"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  mcp-network:
    driver: bridge